module.exports = {
  PORT: parseInt(process.env.PORT) || 3000,

  MAX_PLAYERS: 100,
  MAX_ROOMS: 10,
  MAX_PLAYERS_PER_ROOM: 8,
  MIN_PLAYERS_MAFIA: 5,
  MIN_PLAYERS_SPYFALL: 4,
  MIN_PLAYERS_SECRETH: 5,
  MIN_PLAYERS_LIARS_DICE: 2,
  MAX_PLAYERS_LIARS_DICE: 2,

  CHAT_BUFFER_SIZE: 50,
  CHAT_MSG_MAX_LEN: 140,
  CHAT_USERNAME_MAX_LEN: 16,
  CHAT_RATE_LIMIT_MS: 500,

  DISCUSSION_TIME_MS: 90000,
  VOTING_TIME_MS: 30000,
  SPYFALL_ROUND_TIME_MS: 480000,
  NIGHT_PHASE_TIME_MS: 30000,
  ROLE_REVEAL_TIME_MS: 8000,
  RESULT_DISPLAY_TIME_MS: 10000,
  IDLE_TIMEOUT_MS: 1800000,
  ROLL_REVEAL_TIME_MS: 3000,
  CHALLENGE_REVEAL_TIME_MS: 5000,
  LIARS_DICE_STARTING_DICE: 5,

  GameType: {
    NONE: 0,
    MAFIA: 1,
    SPYFALL: 2,
    SECRET_HITLER: 3,
    LIARS_DICE: 4,
  },

  GamePhase: {
    WAITING: 0,
    ROLE_ASSIGNMENT: 1,
    DISCUSSION: 2,
    NIGHT: 3,
    ACTION: 4,
    VOTING: 5,
    RESULT: 6,
    GAME_OVER: 7,
  },

  MafiaRole: {
    VILLAGER: 0,
    MAFIA: 1,
    DOCTOR: 2,
    DETECTIVE: 3,
  },

  SHRole: {
    LIBERAL: 0,
    FASCIST: 1,
    HITLER: 2,
  },

  SHPower: {
    NONE: 0,
    INVESTIGATE: 1,
    PICK_PRESIDENT: 2,
    PEEK: 3,
    ASSASSINATE: 4,
  },

  SHSubPhase: {
    NOMINATION: 0,
    ELECTION: 1,
    LEGISLATIVE: 2,
    EXECUTIVE: 3,
    RESULT: 4,
  },

  SH_POLICY_DECK_SIZE: 17,
  SH_LIBERAL_POLICIES: 6,
  SH_FASCIST_POLICIES: 11,
};
